[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

# https://peps.python.org/pep-0621/
[tool.poetry]
authors = ["Toni de la Fuente <toni@blyx.com>"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "License :: OSI Approved :: Apache Software License"
]
description = "Prowler is an Open Source security tool to perform Cloud Security best practices assessments, audits, incident response, continuous monitoring, hardening and forensics readiness. It contains more than 240 controls covering CIS, PCI-DSS, ISO27001, GDPR, HIPAA, FFIEC, SOC2, AWS FTR, ENS and custom security frameworks."
license = "Apache-2.0"
maintainers = [
  "Sergio Garcia <sergio@verica.io>",
  "Nacho Rivera <nacho@verica.io>",
  "Pepe Fagoaga <pepe@verica.io>"
]
name = "prowler"
packages = [
  {include = "prowler"}
]
readme = "README.md"
version = "3.2.0"

[tool.poetry.dependencies]
alive-progress = "2.4.1"
arnparse = {version = "0.0.2", optional = true}
azure-identity = {version = "1.12.0", optional = true}
azure-mgmt-authorization = {version = "3.0.0", optional = true}
azure-mgmt-security = {version = "3.0.0", optional = true}
azure-mgmt-storage = {version = "21.0.0", optional = true}
azure-mgmt-subscription = {version = "3.1.1", optional = true}
azure-storage-blob = {version = "12.14.1", optional = true}
boto3 = {version = "1.26.74", optional = true}
botocore = {version = "1.29.74", optional = true}
colorama = "0.4.5"
detect-secrets = {version = "1.4.0", optional = true}
msgraph-core = {version = "0.2.2", optional = true}
pydantic = "1.10.5"
python = "^3.9"
schema = "0.7.5"
shodan = {version = "1.28.0", optional = true}
tabulate = "0.9.0"

[tool.poetry.extras]
all = ["python", "colorama", "pydantic", "schema", "alive-progress", "tabulate", "arnparse", "boto3", "botocore", "detect-secrets", "shodan", "azure-identity", "azure-storage-blob", "msgraph-core", "azure-mgmt-subscription", "azure-mgmt-authorization", "azure-mgmt-security", "azure-mgmt-storage"]
aws = ["arnparse", "boto3", "botocore", "detect-secrets", "shodan"]
azure = ["azure-identity", "azure-storage-blob", "msgraph-core", "azure-mgmt-subscription", "azure-mgmt-authorization", "azure-mgmt-security", "azure-mgmt-storage"]

[tool.poetry.group.dev.dependencies]
bandit = "1.7.4"
black = "22.10.0"
coverage = "7.1.0"
docker = "6.0.0"
flake8 = "5.0.4"
freezegun = "1.2.1"
moto = "4.1.2"
openapi-spec-validator = "0.5.5"
pylint = "2.16.2"
pytest = "7.2.1"
pytest-xdist = "3.2.0"
safety = "2.3.5"
sure = "2.0.1"
vulture = "2.7"

[tool.poetry.scripts]
prowler = "prowler.__main__:prowler"

[tool.poetry.urls]
"Changelog" = "https://github.com/prowler-cloud/prowler/releases"
"Documentation" = "https://docs.prowler.cloud"
"Homepage" = "https://github.com/prowler-cloud/prowler"
"Issue tracker" = "https://github.com/prowler-cloud/prowler/issues"

[tool.poetry-version-plugin]
source = "init"

[tool.pytest.ini_options]
pythonpath = [
  "."
]
